#define ITEM_TYPE_HEALING 	0x01
#define ITEM_TYPE_WINGS 	0x02
#define ITEM_TYPE_SPL_EFF 	0x03


#define ITEM_SPIRIT_LIGHT	0x00
#define ITEM_FRESH_BREAD	0x01
#define ITEM_HONEY_BREAD	0x02
#define ITEM_HEALING_POTION	0x03
#define ITEM_DRAGON_POTION	0x04
#define ITEM_DEW_DROP		0x05
#define ITEM_MINT_LEAVES	0x06
#define ITEM_HEROES_DRINK	0x07
#define ITEM_SILENT_FLUTE	0x08
#define ITEM_CELINES_BELL	0x09
#define ITEM_REPLICA		0x0A
#define ITEM_GIANTS_SHOE	0x0B
#define ITEM_SILVER_AMULET	0x0C
#define ITEM_GOLD_AMULET	0x0D
#define ITEM_WHITE_WINGS	0x0E
#define ITEM_YELLOW_WINGS	0x0F
#define ITEM_BLUE_WINGS		0x10
#define ITEM_GREEN_WINGS	0x11
#define ITEM_RED_WINGS		0x12
#define ITEM_BLACK_WINGS	0x13
#define ITEM_EARTH_ORB		0x14
#define ITEM_WIND_JADE		0x15
#define ITEM_WATER_JEWEL	0x16
#define ITEM_FIRE_RUBY		0x17
#define ITEM_ELTALE_BOOK	0x18
#define ITEM_GOAL_KEY		0x19

struct s_ItemData {
	u16 Usage
	u16 Type
	u16 EffVal1
	u16 EffVal2
	u32 pad
}