/*******************************************
*             VERY UNFINISHED              *
*******************************************/
#define SUBMAP_MELRODE			0X00
#define SUBMAP_MONASTARY_EXT		0X01
#define SUBMAP_FLOATING_MONSATARY	0X02
#define SUBMAP_MELRODE_MAMMON		0X03
#define SUBMAP_MONASTARY_MAMMON		0X04
#define SUBMAP_DONDORAN			0X00
#define SUBMAP_HOLY_PLAIN		0X00
#define SUBMAP_DONDORAN_FLATS		0X00
#define SUBMAP_DONDORAN_SHIP		0X01
#define SUBMAP_LARAPOOL			0X00
#define SUBMAP_LOWER_LARAPOOL		0X01
#define SUBMAP_LARAPOOL_DRAINED		0X02
#define SUBMAP_WEST_CARMAGH		0X00
#define SUBMAP_CARMAGH_SHIP		0X01
#define SUBMAP_NORMOON			0X00